uploads = []
generated = []

[[outputs]]
id = "UqepKePrHrm7ps60OSOMO"
uri = "file://clientes_backup.csv"
type = "table"
title = "Backup Completo — 37 Clientes + 145 Vehículos (CSV)"

[[outputs]]
id = "mRZ6smcTHqoHo9hLNQLu6"
uri = "file://clientes_backup.json"
type = "unspecified"
title = "Backup Completo — 37 Clientes + 145 Vehículos (JSON)"
