uploads = []
generated = []

[[outputs]]
id = "UqepKePrHrm7ps60OSOMO"
uri = "file://clientes_backup.csv"
type = "table"
title = "Backup Clientes — GPS SISTEMA C.A. (CSV)"

[[outputs]]
id = "mRZ6smcTHqoHo9hLNQLu6"
uri = "file://clientes_backup.json"
type = "unspecified"
title = "Backup Clientes — GPS SISTEMA C.A. (JSON)"
